apiVersion: v1
kind: Service
metadata:
  name: ea2-haproxy-academic
  labels:
    app: ea2-haproxy-academic
    app.kubernetes.io/part-of: ea2-haproxy-lab
spec:
  type: NodePort
  selector:
    app: ea2-haproxy-academic
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30088
